services:
  web:
    build: .
    environment:
      IS_DOCKER: "true"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
     - "5000:8080"
    volumes:
      - keyvolume:/root/.aspnet/DataProtection-Keys
    restart: no

  cassandra:
    image: "asm-cassandra"
    ports:
      - "9042:9042"
    volumes:
      - cassandra:/var/lib/cassandra
    restart: always

  neo4j:
    image: "neo4j:enterprise-ubi9"
    ports:
      - "7473:7473"
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
    volumes:
      - neo4j:/data
    restart: always

  ignite:
    image: "apacheignite/ignite"
    ports:
      - "10800:10800"
    restart: always

volumes:
  cassandra:
  keyvolume:
  neo4j:
